export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_EDIT_REQUEST = "USER_EDIT_REQUEST";
export const USER_EDIT_SUCCESS = "USER_EDIT_SUCCESS";
export const USER_EDIT_FAIL = "USER_EDIT_FAIL";

export const USER_GET_PROFILE_REQUEST = "USER_GET_PROFILE_REQUEST";
export const USER_GET_PROFILE_SUCCESS = "USER_GET_PROFILE_SUCCESS";
export const USER_GET_PROFILE_FAIL = "USER_GET_PROFILE_FAIL";

export const USER_GET_PROFILE_ID_REQUEST = "USER_GET_PROFILE_ID_REQUEST";
export const USER_GET_PROFILE_ID_SUCCESS = "USER_GET_PROFILE_ID_SUCCESS";
export const USER_GET_PROFILE_ID_FAIL = "USER_GET_PROFILE_ID_FAIL";

export const USER_FOLLOW_REQUEST = "USER_FOLLOW_REQUEST";
export const USER_FOLLOW_SUCCESS = "USER_FOLLOW_SUCCESS";
export const USER_FOLLOW_FAIL = "USER_FOLLOW_FAIL";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";
